sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

install:
    - export PATH=$PATH:$HOME/local/bin
    - export RUSTFLAGS="-C link-dead-code"
    # Build and cache kcov
    - |
      if [ -f $HOME/local/bin/kcov ]; then
          echo "Using cached kcov from ~/local/bin/kcov"
      else
          mkdir -p $HOME/local
          cd $HOME/local
          wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
          tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ..
          make install
          cd $TRAVIS_BUILD_DIR
      fi
script:
    - cd $TRAVIS_BUILD_DIR
    - cargo test
    - cargo test --release
    - |
      if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
          for test in $(find target/debug/deps/ ! -name "lib*" -type f); do
              kcov --include-pattern=$(pwd) --exclude-pattern=target target/kcov $test
          done
          bash <(curl -s https://codecov.io/bash) -s target/kcov
      fi

cache:
  cargo: true
  directories:
      - $HOME/local/bin
